export const INDUSTRIES = [
  "Construction",
  "Architecture",
  "Urban Development",
  "Infrastructure",
  "Real Estate",
  "Banking & Finance",
  "Insurance",
  "Healthcare",
  "Education",
  "Manufacturing",
  "Energy & Utilities",
  "Transportation & Logistics",
  "Telecommunications",
  "Government & Public Sector",
  "Retail & Consumer Goods",
  "Hospitality & Tourism",
  "Legal & Compliance",
  "IT & Software",
  "Media & Entertainment",
  "Agriculture & Farming",
  "Mining & Natural Resources",
  "Aerospace & Defense",
  "Automotive",
  "Food & Beverage",
  "Environmental Services",
] as const;

export type Industry = (typeof INDUSTRIES)[number];
