import { readFileSync, writeFileSync } from "node:fs";
import { applyRegionalOpenapi } from "./regional-openapi.mjs";

const file = new URL("../openapi.json", import.meta.url);
const spec = JSON.parse(readFileSync(file, "utf8"));
const schema = spec.components.schemas;

for (const name of ["Lead", "CreateLeadInput", "UpdateLeadInput"]) {
  delete schema[name].properties.category;
}
delete schema.DemoRequest.properties.category;
schema.DemoRequest.properties.industry = { type: "string", enum: ["Construction", "Architecture", "Urban Development", "Infrastructure", "Engineering", "Other"], example: "Construction" };

const leadFields = {
  industry: { type: "string", nullable: true, enum: ["Construction", "Architecture", "Urban Development", "Infrastructure", "Engineering", "Other"], example: "Construction" }, region_group: { type: "string", nullable: true, maxLength: 100, description: "Broad global cluster (Americas/EMEA/APAC/Other), populated by the AI/enrichment pipeline. Free text rather than an enum; NULL means enrichment could not confidently determine it.", example: "EMEA" }, region: { type: "string", nullable: true, maxLength: 100, description: "Granular regional classification (e.g. Middle East (GCC) or Latin America), populated by the AI/enrichment pipeline. Free text rather than an enum; NULL means enrichment could not confidently determine it.", example: "UK & Ireland" }, state: { type: "string", nullable: true, maxLength: 100, description: "Administrative subdivision (state, province, department, district) of the lead country, populated by the AI/enrichment pipeline. Free text; NULL means enrichment could not confidently determine it.", example: "Texas" }, country: { type: "string", nullable: true, maxLength: 100, description: "Explicit recorded country, populated by the AI/enrichment pipeline. Free text rather than an enum so any enriched value (e.g. Saudi Arabia, Germany) is accepted; NULL means enrichment could not confidently determine it.", example: "United Kingdom" }, project: { type: "string", nullable: true, example: "LAX Terminal Modernization" },
  project_size: { type: "string", nullable: true, example: "$2.1B" }, project_value: { type: "number", nullable: true, description: "Numeric lead deal size in currency units. NULL means unknown; lower bound of a range when parsed from legacy project_size." }, currency: { type: "string", nullable: true, enum: ["USD", "EUR", "GBP", "NGN"], description: "Explicit source ISO 4217 currency. NULL means unknown; never backfilled from geography." }, application_tools: { type: "array", items: { type: "string" }, example: ["Revit", "Navisworks"] }, temperature: { type: "string", enum: ["hot", "warm", "cool"], example: "hot" }, phase: { type: "string", nullable: true, enum: ["Discovery", "Bid", "In-flight"] },
  lead_status: { type: "string", nullable: true, enum: ["New", "Identified", "Bidding", "Inflight", "Closed"] }, archived: { type: "boolean", example: false },
};
Object.assign(schema.Lead.properties, leadFields);
Object.assign(schema.CreateLeadInput.properties, leadFields, { status: { type: "string", enum: ["new", "contacted", "qualified", "proposal", "negotiation", "won", "lost"], default: "new" }, assigned_to: { type: "integer", nullable: true } });
Object.assign(schema.UpdateLeadInput.properties, leadFields, { status: { type: "string", enum: ["new", "contacted", "qualified", "proposal", "negotiation", "won", "lost"] }, assigned_to: { type: "integer", nullable: true } });
Object.assign(schema.Bid.properties, { lead_id: { type: "string", format: "uuid", nullable: true }, status: { type: "string", example: "Active" } });
Object.assign(schema.Project.properties, { bid_id: { type: "string", format: "uuid", nullable: true }, status: { type: "string", example: "Active" } });
schema.PipelineResponse.properties.stages = {
  type: "array",
  items: {
    type: "object",
    required: ["name", "count", "value", "currency", "pipeline_totals", "leads", "bids"],
    properties: {
      name: { type: "string", enum: ["Discovery", "Qualified", "Proposal", "Negotiation", "Closed Won"] },
      count: { type: "integer", example: 3 },
      value: { type: "number", nullable: true, example: 18000000, description: "Single-currency total when all stage bids share one known source currency (or 0 for no bids); null for mixed or unknown currencies. Never sums currencies together." },
      currency: { type: "string", nullable: true, pattern: "^[A-Z]{3}$", description: "Single source ISO currency only when all stage bids share one; null for mixed or unknown currencies." },
      pipeline_totals: { type: "array", description: "Separate subtotals per known source currency; never combine without conversion.", items: { type: "object", properties: { currency: { type: "string", pattern: "^[A-Z]{3}$" }, currency_symbol: { type: "string", nullable: true }, pipeline_value: { type: "number" }, bid_count: { type: "integer" } } } },
      unknown_currency_bid_count: { type: "integer", description: "Bids with a numeric value whose currency is unknown; excluded from totals." },
      unknown_value_bid_count: { type: "integer", description: "Bids in a known currency whose value is unknown; excluded from totals." },
      leads: { type: "array", items: { $ref: "#/components/schemas/Lead" } },
      bids: { type: "array", items: { $ref: "#/components/schemas/Bid" } },
    },
  },
};
schema.PipelineResponse.required = ["stages", "active_bids", "inflight_projects", "summary"];
schema.Error.properties.errors = { type: "object", additionalProperties: { type: "string" }, example: { region: "Region is required" } };
schema.EmailLog = { type: "object", properties: { id: { type: "string", format: "uuid" }, lead_id: { type: "string", format: "uuid" }, campaign_id: { type: "string", format: "uuid", nullable: true }, recipient: { type: "string", format: "email" }, subject: { type: "string" }, channel: { type: "string", example: "email" }, template: { type: "string" }, status: { type: "string", example: "delivered" }, sent_at: { type: "string", format: "date-time", nullable: true }, delivered_at: { type: "string", format: "date-time", nullable: true }, opened_at: { type: "string", format: "date-time", nullable: true }, clicked_at: { type: "string", format: "date-time", nullable: true }, bounced_at: { type: "string", format: "date-time", nullable: true } } };

const ok = (description, data) => ({ 200: { description, content: { "application/json": { schema: { type: "object", properties: { success: { type: "boolean", example: true }, data } } } } }, 401: { description: "Authentication required" } });
const bearer = [{ bearerAuth: [] }];
const uuid = { name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } };
const leadQuery = ["search", "industry", "region", "project", "project_size", "phase", "lead_status", "status", "temperature", "min_score", "archived", "page", "limit", "sort_by", "sort_order"].map((name) => ({ name, in: "query", schema: { type: ["min_score", "page", "limit"].includes(name) ? "integer" : name === "archived" ? "boolean" : "string" } }));
spec.paths["/api/leads"].get.parameters = leadQuery;
spec.paths["/api/leads"].get.description = "Lists leads with filtering, pagination, and sorting. Sort by company, industry, project, full_name, region, project_size, phase, status, lead_status, score, created_at, or updated_at. `archived` is the archive source of truth.";
spec.paths["/api/leads"].post.requestBody.content["application/json"].example = { full_name: "Michael Okafor", email: "m.okafor@aecom.com", company: "AECOM", industry: "Construction", region_group: "EMEA", region: "UK & Ireland", state: "Greater London", country: "United Kingdom", project: "LAX Terminal Modernization", phase: "Bid", lead_status: "Bidding", status: "qualified", applications: 9, application_tools: ["Revit", "Navisworks"], score: 87, temperature: "hot", archived: false };
spec.paths["/api/leads"].post.responses["409"] = { description: "A lead with this email already exists" };
spec.paths["/api/leads/{id}"].patch.responses["409"] = { description: "A lead with this email already exists" };

spec.paths["/api/leads/import"] = { post: { tags: ["Leads"], summary: "Import leads from CSV", description: "Admin only. Requires full_name and email headers. Matching emails (case-insensitive) update existing leads using non-empty CSV fields; blank or omitted fields preserve saved values. New emails create leads. Repeated emails within the CSV are skipped after the first successful row. Returns created, updated, skipped, failed, and row errors.", security: bearer, requestBody: { required: true, content: { "multipart/form-data": { schema: { type: "object", required: ["file"], properties: { file: { type: "string", format: "binary" } } } } } }, responses: { 200: { description: "Import completed", content: { "application/json": { example: { success: true, data: { created: 4, updated: 2, skipped: 1, failed: 1, errors: [{ row: 7, message: "full_name and a valid email are required" }] } } } } }, 400: { description: "Invalid CSV" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" } } } };
spec.paths["/api/leads/export"] = { get: { tags: ["Leads"], summary: "Export filtered leads as CSV", security: bearer, parameters: ["industry", "region", "project", "project_size", "phase", "lead_status", "status", "temperature", "archived"].map((name) => ({ name, in: "query", schema: { type: name === "archived" ? "boolean" : "string" } })), responses: { 200: { description: "CSV download", content: { "text/csv": { schema: { type: "string", format: "binary" } } } }, 401: { description: "Authentication required" }, 403: { description: "Admin only" } } } };
spec.paths["/api/leads/options"] = { get: { tags: ["Leads"], summary: "Get lead form and filter options", description: "Returns the canonical values for lead dropdowns and filters. countries is derived live from distinct country values currently recorded on leads (empty until enrichment populates them); no static country list is maintained.", security: bearer, responses: ok("Lead options", { type: "object", example: { industries: ["Construction", "Architecture", "Urban Development", "Infrastructure", "Engineering", "Other"], regions: ["North America", "Latin America", "UK & Ireland", "DACH / Northern Europe", "Middle East (GCC)", "Africa", "Southern Europe"], countries: [], project_sizes: ["Under $5M", "$5M-$20M", "$20M-$50M", "$50M-$100M", "$100M-$250M", "$250M-$500M", "$500M-$1B", "$1B+"], phases: ["Discovery", "Bid", "In-flight"], statuses: ["new", "contacted", "qualified", "proposal", "negotiation", "won", "lost"], lead_statuses: ["New", "Identified", "Bidding", "Inflight", "Closed"], temperatures: ["hot", "warm", "cool"] } }) } };
spec.paths["/api/leads/{id}/move-to-pipeline"] = { post: { tags: ["Leads"], summary: "Move a lead to the pipeline", description: "Admin only. Creates an Active bid linked to the lead and changes that lead's status to proposal in one database transaction.", security: bearer, parameters: [uuid], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["project", "client", "phase", "deadline"], properties: { project: { type: "string" }, client: { type: "string" }, phase: { type: "string", enum: ["Discovery", "RFP Review", "Technical Eval", "Shortlist"] }, deadline: { type: "string", format: "date" }, suppliers: { type: "array", items: { type: "string" } }, value: { type: "number", nullable: true } } }, example: { project: "LAX Terminal Modernization", client: "AECOM", phase: "RFP Review", deadline: "2026-10-30", suppliers: ["AECOM", "Bechtel"], value: 2100000000 } } } }, responses: { 201: { description: "Lead moved to pipeline", content: { "application/json": { example: { success: true, data: { bid: { id: "uuid", status: "Active" }, lead: { id: "uuid", status: "proposal" } } } } } }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Lead not found" } } } };
spec.paths["/api/analytics/dashboard"] = { get: { tags: ["Analytics"], summary: "Get dashboard analytics", description: "Returns all data needed by the lead dashboard: KPI cards, industry/application charts, stages, trends, regional coverage, and qualified leads.", security: bearer, parameters: [{ name: "weeks", in: "query", schema: { type: "integer", default: 8, minimum: 1, maximum: 52 } }], responses: ok("Database-driven dashboard", { type: "object", example: { kpis: { lead_growth: 147, qualified_rate: 78.3, email_open_rate: 67.6, click_through: 20.6 }, summary: { total_leads: 3980, pipeline_value: 7300000000, outreach_sent: 3247, conversion_rate: 21.2, countries: 52, active_projects: 487 }, industry_distribution: [{ industry: "Construction", count: 1247 }], application_distribution: [{ application: "Revit", count: 628 }], pipeline_stages: [{ stage: "Discovery", count: 250, pct: 100 }], lead_trend: [], email_engagement: [], regional_coverage: [{ region: "North America", lead_count: 620, pipeline_value: 2800000000 }], qualified_leads: [] } }) } };
for (const region of ["emea", "americas"]) spec.paths[`/api/regions/${region}`] = { get: { tags: ["Regions"], summary: `Get ${region.toUpperCase()} dashboard`, security: bearer, responses: ok("Regional summary", { type: "object", example: { summary: [{ name: "UK & Ireland", lead_count: 420, pipeline_value: 1200000000 }], workflow: [], regions: [] } }) } };
spec.paths["/api/regions"] = { get: { tags: ["Regions"], summary: "List supported lead regions", security: bearer, responses: ok("Region options", { type: "object", example: { regions: ["North America", "Latin America", "UK & Ireland", "DACH / Northern Europe", "Middle East (GCC)", "Africa", "Southern Europe"] } }) } };
spec.paths["/api/campaigns/{id}/stats"] = { get: { tags: ["Campaigns"], summary: "Get campaign event statistics", security: bearer, parameters: [uuid], responses: ok("Campaign statistics", { $ref: "#/components/schemas/CampaignStats" }) } };
spec.paths["/api/outreach/messages"] = { get: { tags: ["Outreach"], summary: "List email messages", security: bearer, parameters: [{ name: "page", in: "query", schema: { type: "integer", default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", default: 20, maximum: 100 } }], responses: ok("Email log list", { type: "object", properties: { messages: { type: "array", items: { $ref: "#/components/schemas/EmailLog" } }, pagination: { $ref: "#/components/schemas/Pagination" } } }) } };
spec.paths["/api/outreach/preview"] = { post: { tags: ["Outreach"], summary: "Preview personalised outreach", security: bearer, requestBody: { required: true, content: { "application/json": { example: { lead_id: "00000000-0000-0000-0000-000000000000", subject: "Hello {{full_name}}", template: "<p>Hello {{full_name}} at {{company}}</p>" } } } }, responses: ok("Preview generated", { type: "object", example: { recipient: "m.okafor@aecom.com", subject: "Hello Michael Okafor", html: "<p>Hello Michael Okafor at AECOM</p>" } }) } };
spec.paths["/api/outreach/send"] = { post: { tags: ["Outreach"], summary: "Send personalised outreach", security: bearer, requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["lead_id", "subject", "template"], properties: { lead_id: { type: "string", format: "uuid" }, campaign_id: { type: "string", format: "uuid", nullable: true }, subject: { type: "string" }, template: { type: "string" } } } } } }, responses: { ...ok("Message sent", { $ref: "#/components/schemas/EmailLog" }), 201: { description: "Message sent" }, 503: { description: "Email provider not configured" } } } };
spec.paths["/api/webhooks/resend"] = { post: { tags: ["Webhooks"], summary: "Receive verified Resend events", description: "Resend Svix-signed webhook endpoint.", security: [], responses: { 200: { description: "Event processed" }, 401: { description: "Invalid signature" }, 503: { description: "Webhook secret is not configured" } } } };
spec.paths["/api/pipeline"].get.description = "Returns Deal Flow stages based on live lead status, plus active bids and in-flight projects. Stages are Discovery, Qualified, Proposal, Negotiation, and Closed Won. Each stage contains its lead cards, linked active bids, and the linked bid-value total.";

for (const name of ["Bid", "CreateBidInput", "UpdateBidInput"]) {
  Object.assign(schema[name].properties, {
    lead_id: { type: "string", format: "uuid", nullable: true, description: "Existing lead ID. At most one bid per linked lead." },
    value: { type: "number", nullable: true, description: "Actual bid amount. Zero is valid; null means unconfirmed. Independent of lead.project_size." },
    suppliers: { type: "array", items: { type: "string" }, description: "Supplier names; empty when unconfirmed." },
    status: { type: "string", ...(name === "CreateBidInput" ? { default: "Active" } : {}) },
  });
}
schema.CreateBidInput.required = ["project", "client", "phase", "deadline"];
spec.paths["/api/bids"].post.description = "Admin only. Create a bid using project, client, phase, and deadline. Supply lead_id to link an existing lead without changing its status or project_size. value defaults to null and suppliers to []. Duplicate lead links return 409; update the existing bid instead.";
spec.paths["/api/bids/{id}"].patch.description = "Admin only. Update one or more bid fields, including value (number or null), suppliers (array of names), and lead_id. Omitted fields are preserved. Does not change the linked lead's status or project_size.";
for (const operation of [spec.paths["/api/bids"].post, spec.paths["/api/bids/{id}"].patch]) {
  operation.responses[409] = { description: "The lead already has a bid. Update that bid instead." };
  operation.responses[404] = { description: "Bid or linked lead not found." };
}
spec.paths["/api/pipeline"].get.description = "Returns stages determined by lead status. Each stage includes all bids linked to its leads, regardless of bid status, with lead_id, nullable numeric value, currency, and suppliers. A stage currency is reported only when every linked bid shares one source ISO currency; mixed or unknown currencies report null. The separate active_bids list and summary remain limited to active bids.";

spec.paths["/api/leads/import"].post.description += " Optional bid_value (plain number, 0 valid, or literal null) and suppliers (semicolon-separated names or JSON array; [] clears) create/update the bid linked to the lead ID. Blank bid cells preserve existing details. Creating a bid also requires bid_phase and bid_deadline, plus bid_project/bid_client or the lead's project/company. Bid import preserves lead status and project_size. Lead and bid writes are separate; bids_failed and row errors report bid failures even when the lead was saved and HTTP status is 200.";
Object.assign(spec.paths["/api/leads/import"].post.responses[200].content["application/json"].example.data, { bids_created: 1, bids_updated: 1, bids_failed: 0 });

spec.paths["/api/leads/export"].get.description = "Exports lead fields plus bid_value, suppliers (JSON array in a CSV cell), bid_phase, bid_deadline, bid_project, and bid_client. Bids match lead_id regardless of bid status. Zero is preserved; unknown bid amount is literal null; no linked bid produces blank bid fields. Project size remains separate. Multiple linked bids export as separate rows with repeated lead fields and bid_id. bid_id is informational; imports still reject ambiguous multiple-bid links.";
delete spec.paths["/api/leads/export"].get.responses[409];

for (const name of ["CreateBidInput", "UpdateBidInput"]) {
  schema[name].properties.deadline = { type: "string", format: "date", description: "A real calendar date in YYYY-MM-DD format. Slash dates and impossible dates are rejected." };
}
spec.paths["/api/leads/import"].post.description += " Bid validation errors identify the CSV field. bid_deadline must be a real YYYY-MM-DD date. Partial saves return HTTP 200 with success:false, partial_success:true, top-level errors (also in data.errors), and the first error in message. Full success returns success:true and partial_success:false. No-save failures return 400/409 with partial_success:false.";
const importExample = spec.paths["/api/leads/import"].post.responses[200].content["application/json"].example;
importExample.success = false;
importExample.partial_success = true;
importExample.errors = importExample.data.errors;
importExample.message = "Import partially completed. Some rows were saved; review errors for failed rows.";

const projectStatuses = ["Active", "In-flight", "On Hold", "Completed", "Cancelled"];
const projectPhases = ["Planning", "Design", "Construction", "In Progress", "Completed"];
for (const name of ["Project", "CreateProjectInput", "UpdateProjectInput"]) {
  Object.assign(schema[name].properties, {
    status: { type: "string", enum: projectStatuses, ...(name === "CreateProjectInput" ? { default: "Active" } : {}) },
    bid_id: { type: "string", format: "uuid", nullable: true },
    progress: { type: "number", minimum: 0, maximum: 100 },
    suppliers: { type: "array", items: { type: "string" } },
    uses_3d: { type: "boolean" },
    competitor: { type: "string", nullable: true },
    issue: { type: "string", nullable: true, description: "Single issues text field, not an array." },
    phase: { type: "string", enum: projectPhases, ...(name === "CreateProjectInput" ? { default: "Planning" } : {}) },
    value: { type: "number", nullable: true },
    currency: { type: "string", nullable: true },
  });
}
spec.paths["/api/projects"].post.description = "Admin only. Requires project, client, start_date, end_date. Saves progress (0–100), supplier names, uses_3d, competitor, issue, bid_id and status. Status defaults to Active; only In-flight appears in pipeline inflight_projects.";
spec.paths["/api/projects/{id}"].patch.description = "Admin only. Send one or more project fields. Omitted fields are preserved. Allowed status values: Active, In-flight, On Hold, Completed, Cancelled. Refetch GET /api/pipeline after saving; only In-flight projects appear in inflight_projects, with all saved fields.";
spec.paths["/api/pipeline"].get.description += " inflight_projects contains full saved projects with status In-flight; Active, On Hold, Completed and Cancelled are excluded.";

spec.paths["/api/analytics/dashboard"].get.description += " Regional coverage includes won_deal_value: total linked bid amounts for non-archived leads with status won, grouped by region and sorted highest first. Null amounts contribute zero. This is won deal value, not payments received; project_size is never used. Frontend should display won_deal_value as money rather than a percentage. Existing regional pipeline_value retains all linked deal amounts. Each region reports currency only when all its linked bids share one source currency; mixed or unknown currencies report null.";
const dashboardExample = spec.paths["/api/analytics/dashboard"].get.responses[200].content["application/json"].schema.properties.data.example;
dashboardExample.regional_coverage = [{ region: "Africa", lead_count: 3, pipeline_value: 95000, won_deal_value: 15000, currency: "USD" }];

const supplierProperties = {
  name: { type: "string", minLength: 1 }, role: { type: "string", nullable: true },
  tools: { type: "array", items: { type: "string" } },
  temperature: { type: "string", nullable: true, enum: ["hot", "warm", "cool"] },
  contact: { type: "object", properties: { name: { type: "string", nullable: true }, job_title: { type: "string", nullable: true }, email: { type: "string", format: "email", nullable: true } } },
  visualisation_tool: { type: "string", nullable: true }, uses_3d: { type: "boolean", nullable: true },
  opportunity: { type: "string", nullable: true }, pain_points: { type: "array", items: { type: "string" } },
};
schema.Supplier = { type: "object", properties: { id: { type: "string", format: "uuid" }, ...supplierProperties } };
schema.ActiveBid = { allOf: [{ $ref: "#/components/schemas/Bid" }, { type: "object", required: ["supplier_details"], properties: { supplier_details: { type: "array", items: { $ref: "#/components/schemas/Supplier" } } } }] };
schema.PipelineResponse.properties.active_bids = { type: "array", items: { $ref: "#/components/schemas/ActiveBid" } };
const supplierResponse = ok("Supplier profile", { type: "object", properties: { supplier: { $ref: "#/components/schemas/Supplier" } } });
spec.paths["/api/suppliers"] = {
  get: { tags: ["Suppliers"], security: bearer, summary: "List supplier profiles", parameters: ["page", "limit"].map(name => ({ name, in: "query", schema: { type: "integer", minimum: 1 } })), responses: ok("Supplier list", { type: "object", properties: { suppliers: { type: "array", items: { $ref: "#/components/schemas/Supplier" } }, pagination: { $ref: "#/components/schemas/Pagination" } } }) },
  post: { tags: ["Suppliers"], security: bearer, summary: "Create supplier (admin)", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name"], properties: supplierProperties } } } }, responses: { 201: supplierResponse[200], 400: { description: "Invalid profile" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" } } },
};
spec.paths["/api/suppliers/{id}"] = {
  get: { tags: ["Suppliers"], security: bearer, summary: "Get supplier", parameters: [uuid], responses: { ...supplierResponse, 404: { description: "Supplier not found" } } },
  patch: { tags: ["Suppliers"], security: bearer, summary: "Edit supplier (admin)", description: "Omitted top-level fields are preserved. Supplied contact replaces the entire contact object. Unknown scalar fields are null; unknown lists are empty.", parameters: [uuid], requestBody: { required: true, content: { "application/json": { schema: { type: "object", minProperties: 1, properties: supplierProperties } } } }, responses: { ...supplierResponse, 400: { description: "Invalid profile" }, 403: { description: "Admin only" }, 404: { description: "Supplier not found" } } },
};
spec.paths["/api/bids/{id}/suppliers/{supplierId}"] = Object.fromEntries(["put", "delete"].map(method => [method, { tags: ["Suppliers"], security: bearer, summary: method === "put" ? "Link existing supplier to bid (admin, idempotent)" : "Unlink supplier from bid (admin)", parameters: [uuid, { name: "supplierId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Link saved" }, 400: { description: "Invalid UUID" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Bid or supplier not found" } } }]));
spec.paths["/api/projects/{id}/suppliers/{supplierId}"] = Object.fromEntries(["put", "delete"].map(method => [method, { tags: ["Projects"], security: bearer, summary: method === "put" ? "Link supplier to project (admin, idempotent)" : "Unlink supplier from project (admin)", parameters: [uuid, { name: "supplierId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Link saved" }, 400: { description: "Invalid UUID" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Project or supplier not found" } } }]));
spec.paths["/api/pipeline"].get.description += " Each active bid includes supplier_details from explicitly linked supplier profiles. suppliers retains legacy names plus linked profile names. Unlinked names are not converted into fabricated profiles. Apply supplier-migration.sql before deploying.";

spec.paths["/api/analytics/dashboard"].get.description += " data.leads_by_application is an array of {application, lead_count} across all non-archived leads (all lifecycle statuses). Counts each lead once per trimmed, case-insensitive application_tools name, ignores blanks, and returns [] without data. Sorted by descending count then name; display casing uses the first encountered name in lead-ID order. Existing application_distribution is preserved.";
dashboardExample.leads_by_application = [{ application: "Revit", lead_count: 2 }, { application: "AutoCAD", lead_count: 1 }];
const dashboardDataSchema = spec.paths["/api/analytics/dashboard"].get.responses[200].content["application/json"].schema.properties.data;
dashboardDataSchema.properties = { ...dashboardDataSchema.properties, leads_by_application: { type: "array", items: { type: "object", required: ["application", "lead_count"], properties: { application: { type: "string" }, lead_count: { type: "integer", minimum: 0 } } } } };

spec.paths["/api/leads/export"].get.parameters = spec.paths["/api/leads/export"].get.parameters.filter(parameter => ["region", "phase", "project_size", "temperature", "archived"].includes(parameter.name));
for (const name of ["CreateBidInput", "UpdateBidInput"]) {
  schema[name].properties.status.description = "Any nonempty string is currently accepted. Defaults to Active on creation; active_bids includes only status Active (case-insensitive). No fixed bid-status enum is enforced.";
}

schema.SupplierSummary = { allOf: [{ $ref: "#/components/schemas/Supplier" }, { type: "object", properties: { active_project_count: { type: "integer", minimum: 0 }, regions: { type: "array", items: { type: "string" } } } }] };
schema.SupplierIntelligence = { allOf: [{ $ref: "#/components/schemas/SupplierSummary" }, { type: "object", properties: {
  active_projects: { type: "array", items: { type: "object", required: ["id", "name", "client", "status", "phase", "value", "currency"], properties: { id: { type: "string", format: "uuid" }, name: { type: "string" }, client: { type: "string" }, status: { type: "string", enum: projectStatuses }, phase: { type: "string", enum: projectPhases }, value: { type: "number", nullable: true }, currency: { type: "string", nullable: true } } } },
  related_suppliers: { type: "array", items: { type: "object", properties: { id: { type: "string", format: "uuid" }, name: { type: "string" }, role: { type: "string", nullable: true }, shared_project_count: { type: "integer", minimum: 1 } } } },
  opportunities: { type: "array", items: { type: "object", properties: { id: { type: "string", format: "uuid" }, name: { type: "string" }, project: { type: "string", nullable: true }, value: { type: "number", nullable: true }, currency: { type: "string", nullable: true }, insight: { type: "string", nullable: true }, status: { type: "string", enum: ["open", "qualified", "won", "lost"] } } } },
} }] };
spec.paths["/api/suppliers/{id}"].get.description = "Adds active_projects (Active/In-flight), related_suppliers with distinct shared_project counts across all statuses, and standalone opportunities. Empty relationships return []. Apply supplier-migration.sql before using opportunity data.";

const opportunityProperties = {
  id: { type: "string", format: "uuid" }, supplier_id: { type: "string", format: "uuid" },
  lead_id: { type: "string", format: "uuid", nullable: true }, project_id: { type: "string", format: "uuid", nullable: true }, bid_id: { type: "string", format: "uuid", nullable: true },
  name: { type: "string", minLength: 1 }, description: { type: "string", nullable: true }, insight: { type: "string", nullable: true },
  status: { type: "string", enum: ["open", "qualified", "won", "lost"] }, value: { type: "number", nullable: true }, currency: { type: "string", nullable: true },
  created_at: { type: "string", format: "date-time" }, updated_at: { type: "string", format: "date-time" },
};
schema.Opportunity = { type: "object", properties: opportunityProperties };
const opportunitySummary = { type: "object", required: ["id", "name", "project", "value", "currency", "insight", "status"], properties: { id: opportunityProperties.id, name: opportunityProperties.name, project: { type: "string", nullable: true }, value: opportunityProperties.value, currency: opportunityProperties.currency, insight: opportunityProperties.insight, status: opportunityProperties.status } };
const opportunityPagination = { type: "object", properties: { opportunities: { type: "array", items: opportunitySummary }, pagination: { $ref: "#/components/schemas/Pagination" } } };
spec.paths["/api/suppliers/{supplierId}/opportunities"] = { get: { tags: ["Opportunities"], summary: "List supplier opportunities", security: bearer, parameters: [{ name: "supplierId", in: "path", required: true, schema: { type: "string", format: "uuid" } }, { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } }], responses: { 200: { description: "Supplier opportunities", content: { "application/json": { schema: { type: "object", properties: { success: { type: "boolean" }, data: opportunityPagination } }, example: { success: true, data: { opportunities: [{ id: "uuid", name: "Airport expansion", project: "LAX Terminal Modernization", value: 2500000, currency: "USD", insight: "Early design influence", status: "qualified" }], pagination: { page: 1, limit: 20, total: 1, pages: 1 } } } } } }, 401: { description: "Authentication required" }, 404: { description: "Supplier not found" } } } };
const opportunityRequest = { type: "object", required: ["supplier_id", "name"], properties: { supplier_id: opportunityProperties.supplier_id, lead_id: opportunityProperties.lead_id, project_id: opportunityProperties.project_id, bid_id: opportunityProperties.bid_id, name: opportunityProperties.name, description: opportunityProperties.description, insight: opportunityProperties.insight, status: { ...opportunityProperties.status, default: "open" }, value: opportunityProperties.value, currency: opportunityProperties.currency } };
spec.paths["/api/opportunities"] = { post: { tags: ["Opportunities"], summary: "Create opportunity (admin)", security: bearer, requestBody: { required: true, content: { "application/json": { schema: opportunityRequest, example: { supplier_id: "uuid", lead_id: null, project_id: "uuid", bid_id: null, name: "Airport expansion", description: "Potential visualization work", insight: "Early design influence", status: "open", value: 2500000, currency: "USD" } } } }, responses: { 201: { description: "Opportunity created", content: { "application/json": { example: { success: true, data: { opportunity: { id: "uuid", supplier_id: "uuid", name: "Airport expansion", status: "open", value: 2500000, currency: "USD" } } } } } }, 400: { description: "Validation failed" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Supplier or linked record not found" } } } };
spec.paths["/api/opportunities"].get = { tags: ["Opportunities"], summary: "Search opportunities", description: "Authenticated users can search opportunity names, descriptions, and insights. Results are paginated.", security: bearer, parameters: [{ name: "search", in: "query", schema: { type: "string" }, description: "Case-insensitive text search" }, { name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } }], responses: { 200: { description: "Opportunity list", content: { "application/json": { example: { success: true, data: { opportunities: [{ id: "uuid", supplier_id: "uuid", name: "Airport expansion", project: "LAX Terminal Modernization", status: "open", value: 2500000, currency: "USD" }], pagination: { page: 1, limit: 20, total: 1, pages: 1 } } } } } }, 401: { description: "Authentication required" } } };
spec.paths["/api/opportunities/{id}"] = { get: { tags: ["Opportunities"], summary: "Get opportunity", security: bearer, parameters: [uuid], responses: { 200: { description: "Opportunity", content: { "application/json": { example: { success: true, data: { opportunity: { id: "uuid", supplier_id: "uuid", lead_id: null, project_id: null, bid_id: null, name: "Airport expansion", description: null, insight: "Early design influence", status: "open", value: null, currency: null, created_at: "2026-09-10T12:00:00.000Z", updated_at: "2026-09-10T12:00:00.000Z" } } } } } }, 401: { description: "Authentication required" }, 404: { description: "Opportunity not found" } } }, patch: { tags: ["Opportunities"], summary: "Edit opportunity (admin)", security: bearer, parameters: [uuid], requestBody: { required: true, content: { "application/json": { schema: { ...opportunityRequest, required: [] }, example: { status: "won", value: 0 } } } }, responses: { 200: { description: "Opportunity updated" }, 400: { description: "Validation failed" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Opportunity not found" } } }, delete: { tags: ["Opportunities"], summary: "Delete opportunity (admin)", security: bearer, parameters: [uuid], responses: { 200: { description: "Opportunity deleted" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Opportunity not found" } } } };
spec.paths["/api/opportunities/{id}/suppliers/{supplierId}"] = Object.fromEntries(["put", "delete"].map(method => [method, { tags: ["Opportunities"], summary: method === "put" ? "Link supplier to opportunity (admin)" : "Unlink supplier from opportunity (admin)", security: bearer, parameters: [uuid, { name: "supplierId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Supplier link updated" }, 400: { description: "Invalid UUID" }, 401: { description: "Authentication required" }, 403: { description: "Admin only" }, 404: { description: "Opportunity or supplier not found" } } } ]));
spec.paths["/api/suppliers"].get.responses = ok("Supplier intelligence", { type: "object", properties: { suppliers: { type: "array", items: { $ref: "#/components/schemas/SupplierIntelligence" } }, pagination: { $ref: "#/components/schemas/Pagination" } } });
spec.paths["/api/suppliers/{id}"].get.responses = { ...ok("Supplier intelligence", { type: "object", properties: { supplier: { $ref: "#/components/schemas/SupplierIntelligence" } } }), 404: { description: "Supplier not found" } };
spec.paths["/api/suppliers"].get.description = "Includes active_project_count and active_projects for projects with lifecycle status Active or In-flight. Relationships use project_suppliers IDs when present and trimmed, case-insensitive legacy supplier names as a compatibility fallback.";
spec.paths["/api/suppliers/{id}"].get.description = "Adds active_project_count and active_projects for projects with lifecycle status Active or In-flight. Each project includes its lifecycle status, phase, nullable value, and currency. Empty relationships return active_project_count 0 and active_projects [].";

applyRegionalOpenapi(spec);
writeFileSync(file, `${JSON.stringify(spec, null, 2)}\n`);
